# version: '3.8'
services:

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: chat_keycloak
    command: ["start-dev", "--http-relative-path=/", "--import-realm", "--hostname-strict=false"]
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
    ports:
      - "8081:8080"   # accès local: http://localhost:8081/
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    healthcheck:
#      test: ["CMD-SHELL", "(command -v curl >/dev/null 2>&1 && curl -fsS http://localhost:8080/health/ready >/dev/null) || (command -v wget >/dev/null 2>&1 && wget -qO- http://localhost:8080/health/ready >/dev/null) || exit 1"]
      test: "{ printf >&3 'GET /realms/demo/.well-known/openid-configuration HTTP/1.0\r\nHost: localhost\r\n\r\n'; cat <&3; } 3<>/dev/tcp/localhost/8080 | head -1 | grep 200"
      interval: 10s
      timeout: 5s
      retries: 60
      start_period: 120s
    networks:
      - chat-net

  db:
    image: postgres:16
    container_name: chat_db
    environment:
      POSTGRES_USER: chat
      POSTGRES_PASSWORD: chat
      POSTGRES_DB: chat
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chat -d chat"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - chat-net

  backend:
    build: ./backend
    container_name: chat_backend
    depends_on:
      db:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    environment:
      OIDC_ISSUER_URI: http://keycloak:8080/realms/demo
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/demo/protocol/openid-connect/certs
      OIDC_CLIENT_ID: chat-app
      OIDC_CLIENT_SECRET: ""    # client public (PKCE)
      OIDC_PROVIDER_ID: oidc
      OIDC_LOGOUT_REDIRECT_URI: http://localhost:9080/
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/chat
      SPRING_DATASOURCE_USERNAME: chat
      SPRING_DATASOURCE_PASSWORD: chat
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SERVER_PORT: 8080
      # SERVER_PORT doit matcher le port utilisé au build du container (8080), pas le port souhaité au runtime 9080)
      # Cette variable sert pour maven (utilisée dans les fichiers .properties)
      # La surcharge de cette variable est nécessaire pour les tests de backend en dev (hors contexte docker compose)
      # Dans un contexte docker compose, laisser le port 8080, et surcharger au niveau "ports"
      CORS_ALLOWED_ORIGINS: 
        http://localhost,
        http://localhost:80,
        http://localhost:8888,
        http://127.0.0.1:8888,
        http://localhost:8080,
        http://localhost:9080,
        http://localhost:4200,
        http://frontend
    ports:
      - "9080:8080"
    networks:
      - chat-net

  frontend:
    build: ./frontend
    container_name: chat_frontend
    depends_on:
      - backend
    ports:
      - "8888:80"
    environment:
      API_BASE_URL: http://localhost:9080
    networks:
      - chat-net

  prometheus:
    image: prom/prometheus:latest
    container_name: chat_prometheus
    volumes:
      - ./prometheus/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - backend
    networks:
      - chat-net

  grafana:
    image: grafana/grafana-oss:latest
    container_name: chat_grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/datasources/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
      - ./monitoring/grafana/dashboards/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml:ro
      - ./monitoring/grafana/dashboards/jvm_http_hikari.json:/etc/grafana/provisioning/dashboards/jvm_http_hikari.json:ro
    networks:
      - chat-net

  # (optionnel) métriques des conteneurs Docker
  cadvisor:
    profiles: ["linux-host-metrics"]
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: chat_cadvisor
    ports:
      - "8088:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    networks:
      - chat-net

  # (optionnel) métriques “OS” du host (dans Docker c’est souvent accessoire)
  node-exporter:
    profiles: ["linux-host-metrics"]
    image: prom/node-exporter:latest
    container_name: chat_node_exporter
    ports:
      - "9100:9100"
    command:
      - '--path.rootfs=/host'
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - chat-net

volumes:
  grafana_data:
  db_data:

networks:
  chat-net:
    driver: bridge
