# Chat App — Makefile (Docker Compose + Local Dev)
# Usage examples:
#   make up
#   make smoke TOKEN=eyJ...
#   make backend-test
#   make frontend-serve

# -------- Variables --------
DC ?= docker compose
FRONT_DIR ?= frontend
BACK_DIR ?= backend
SCRIPTS_DIR ?= scripts
ENV_FILE ?= .env

# Allow overriding ports/host for smoke tests
HOST ?= localhost
API_PORT ?= 9080
FRONT_PORT ?= 8888
KC_PORT ?= 8081
TOKEN ?=

# -------- Helper --------
.PHONY: help
help: ## Show this help
	@awk 'BEGIN {FS = ":.*##"; printf "\nTargets:\n"} /^[a-zA-Z0-9_\-]+:.*?##/ { printf "  \033[36m%-22s\033[0m %s\n", $$1, $$2 }' $(MAKEFILE_LIST)

# -------- Docker Compose lifecycle --------
.PHONY: up
up: ## Start the full stack (build if needed)
	$(DC) up -d --build

.PHONY: up-build
up-build: ## Rebuild and start (no cache)
	$(DC) build --no-cache
	$(DC) up -d

.PHONY: down
down: ## Stop and remove containers, networks
	$(DC) down

.PHONY: restart
restart: ## Restart the stack
	$(DC) down
	$(DC) up -d --build

.PHONY: ps
ps: ## Show compose services status
	$(DC) ps

.PHONY: logs
logs: ## Tail all services logs
	$(DC) logs -f

.PHONY: logs-backend
logs-backend: ## Tail backend logs
	$(DC) logs -f backend

.PHONY: logs-frontend
logs-frontend: ## Tail frontend logs
	$(DC) logs -f frontend

.PHONY: logs-keycloak
logs-keycloak: ## Tail keycloak logs
	$(DC) logs -f keycloak

.PHONY: prune
prune: ## Prune dangling images/volumes (careful)
	docker system prune -f
	docker volume prune -f || true

# -------- Smoke tests --------
.PHONY: smoke
smoke: ## Run smoke tests (requires TOKEN for protected calls)
	HOST=$(HOST) API_PORT=$(API_PORT) FRONT_PORT=$(FRONT_PORT) KC_PORT=$(KC_PORT) TOKEN=$(TOKEN) bash $(SCRIPTS_DIR)/smoke-tests.sh

# -------- Local backend (outside Docker) --------
.PHONY: backend-build
backend-build: ## Build backend with Maven (multi-module)
	cd $(BACK_DIR) && mvn -q -DskipTests package

.PHONY: backend-test
backend-test: ## Run backend unit tests
	cd $(BACK_DIR) && mvn -q -DskipITs test

.PHONY: backend-it
backend-it: ## Run backend integration tests (profile it)
	cd $(BACK_DIR) && mvn -q -Pit verify

.PHONY: backend-dev-run
backend-dev-run: ## Run backend locally (dev profile)
	cd $(BACK_DIR)/app && mvn -q spring-boot:run -Dspring-boot.run.profiles=dev

# -------- Local frontend (outside Docker) --------
.PHONY: frontend-install
frontend-install: ## Install frontend deps
	cd $(FRONT_DIR) && npm ci

.PHONY: frontend-build
frontend-build: ## Build frontend for production
	cd $(FRONT_DIR) && npm run build

.PHONY: frontend-serve
frontend-serve: ## Serve frontend locally (Angular dev server)
	cd $(FRONT_DIR) && npm run start

# -------- Keycloak helpers --------
.PHONY: keycloak-restart
keycloak-restart: ## Restart Keycloak service
	$(DC) restart keycloak

.PHONY: keycloak-admin
keycloak-admin: ## Open Keycloak Admin in browser
	@echo "Open: http://localhost:$(KC_PORT)/"

# -------- Utilities --------
.PHONY: clean
clean: ## Remove build artifacts (frontend dist + backend targets)
	rm -rf $(FRONT_DIR)/dist || true
	find $(BACK_DIR) -type d -name target -exec rm -rf {} + || true

.PHONY: tidy
tidy: ## Format/readability tasks (placeholder)
	@echo "(Add formatters or linters here if needed)"


.PHONY: env
env: ## Generate a fresh .env file with sensible defaults (overwrites existing)
	@echo "Generating .env with defaults..."
	@printf "%s\n" \
"# --- Chat App .env (generated by make env) ---" \
"" \
"# Spring profiles (backend)" \
"SPRING_PROFILES_ACTIVE=prod" \
"" \
"# OIDC / JWT" \
"OIDC_ISSUER_URI=http://keycloak:8080/realms/demo" \
"SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/realms/demo/protocol/openid-connect/certs" \
"" \
"# CORS (comma-separated list)" \
"CORS_ALLOWED_ORIGINS=http://localhost,http://localhost:8888,http://127.0.0.1:8888" \
"" \
"# Backend server port (internal Spring port; compose maps 9080:8080)" \
"SERVER_PORT=8080" \
"" \
"# Database" \
"SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/chat" \
"SPRING_DATASOURCE_USERNAME=chat" \
"SPRING_DATASOURCE_PASSWORD=chat" \
"" \
"# Frontend" \
"API_BASE_URL=http://localhost:9080" \
"" \
"# Keycloak (UI on host)" \
"KC_PORT=8081" \
"" \
"# Optional: logging levels (uncomment to tweak)" \
"# LOGGING_LEVEL_ROOT=INFO" \
"# LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=DEBUG" \
> .env
	@echo ".env generated."


.PHONY: env-dev
env-dev: ## Generate a .env.dev file for development (coexists with .env)
	@echo "Generating .env.dev (development settings)..."
	@printf "%s\n" \
"# --- Chat App .env.dev (generated by make env-dev) ---" \
"" \
"# Spring profiles (backend) - development" \
"SPRING_PROFILES_ACTIVE=dev" \
"" \
"# OIDC / JWT" \
"OIDC_ISSUER_URI=http://keycloak:8080/realms/demo" \
"SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/realms/demo/protocol/openid-connect/certs" \
"" \
"# CORS (dev: permissive patterns + common origins)" \
"CORS_ALLOWED_ORIGINS=http://localhost,http://localhost:8888,http://127.0.0.1:8888,http://localhost:4200,*" \
"# NOTE: '*' est accepté via allowedOriginPatterns côté backend (pas de credentials)" \
"" \
"# Backend server port (internal Spring port; compose maps 9080:8080)" \
"SERVER_PORT=8080" \
"" \
"# Database (dev can still use containerized Postgres)" \
"SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/chat" \
"SPRING_DATASOURCE_USERNAME=chat" \
"SPRING_DATASOURCE_PASSWORD=chat" \
"" \
"# Frontend" \
"API_BASE_URL=http://localhost:9080" \
"" \
"# Logging (more verbose for debugging)" \
"LOGGING_LEVEL_ROOT=DEBUG" \
"LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=DEBUG" \
"LOGGING_LEVEL_ORG_HIBERNATE_SQL=DEBUG" \
> .env.dev
	@echo ".env.dev generated."
