global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'chat-backend'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['backend:9080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # Décommenter si lancement avec le profil Linux
  #- job_name: 'cadvisor'
  #  static_configs:
  #    - targets: ['cadvisor:8080']
  #
  #- job_name: 'node-exporter'
  #  static_configs:
  #    - targets: ['node-exporter:9100']