server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework # Pour respecter les en-têtes X-Forwarded-* du proxy
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate # on laisse flyway générer le schéma
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true # mettez false si vos DBA migrent séparément
    locations: classpath:db/migration
    baseline-on-migrate: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OIDC_ISSUER_URI:https://localhost/keycloak/realms/demo}
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCE_SERVER_JWT_JWK_SET_URI:https://localhost/keycloak/realms/demo/protocol/openid-connect/certs}

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized # en dev: 'always' si tu veux
  metrics:
    tags:
      application: chat-backend
      profile: ${spring.profiles.active:default}
  prometheus:
    metrics:
      export:
        enabled: true
