server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework      # Pour respecter les en-têtes X-Forwarded-* du proxy

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OIDC_ISSUER_URI:http://localhost:8081/realms/demo}
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCE_SERVER_JWT_JWK_SET_URI:http://localhost:8081/realms/demo/protocol/openid-connect/certs}

# Logs plus verbeux en IT si besoin
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
